---
- name: Transfer Ansible Public Key
  hosts: all
  become: yes
  tasks:
    - name: Ensure SSH directory exists
      file:
        path: "~/.ssh"
        state: directory


    - name: Copy Ansible public key to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
