---
- name: Transfer SSH Key
  hosts: all
  become: yes
  tasks:
    - name: Ensure SSH directory exists
      become_user: "{{ ansible_user }}"
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
      register: ssh_dir_result
      
    - name: Copy SSH key to remote host
      become_user: "{{ ansible_user }}"
      copy:
        src: /home/ansibletest/.ssh/id_rsa.pub
        dest: "~/.ssh/authorized_keys"
      register: copy_result

