- name: Check Cs
  hosts: all

  tasks:
    - name: Execute ps command
      shell: ps -e | grep falcon-sensor
      register: ps_output
      ignore_errors: yes

    - name: Display ps command output
      debug:
        msg: "{{ ps_output.stdout | default('none', true) }}"
