---
- name: Transfer and run Python script
  hosts: all
  gather_facts: yes

  tasks:
    - name: Determine OS type
      set_fact:
        os_type: "{{ ansible_facts['distribution'] }}"

    - name: Check if python3-setuptools is installed
      command: "python3 -c 'import setuptools'"
      register: setuptools_check
      ignore_errors: true

    - name: Install python3-setuptools if not present (CentOS/RedHat)
      package:
        name: python3-setuptools
        state: present
      become: yes
      when: os_type in ['CentOS', 'RedHat'] and setuptools_check.rc != 0

    - name: Install python3-setuptools if not present (Ubuntu)
      package:
        name: python3-setuptools
        state: present
      become: yes
      when: os_type == 'Ubuntu' and setuptools_check.rc != 0

    - name: Check if pymysql is installed
      command: "python3 -c 'import pymysql'"
      register: pymysql_check
      ignore_errors: true

    - name: Check if pip3 is installed
      command: which pip3
      register: pip3_check
      ignore_errors: true

    - name: Install pip3 if not present
      package:
        name: python3-pip
        state: present
      become: yes
      when: pip3_check.rc != 0

    - name: Install pymysql if not present (CentOS/RedHat)
      command: pip3 install pymysql
      become: yes
      when: os_type in ['CentOS', 'RedHat'] and pymysql_check.rc != 0 and pip3_check.rc == 0

    - name: Install pymysql if not present (Ubuntu)
      command: pip3 install pymysql
      become: yes
      when: os_type == 'Ubuntu' and pymysql_check.rc != 0 and pip3_check.rc == 0


