---
- name: Transfer and run Python script
  hosts: all
  gather_facts: yes

  tasks:
    - name: Determine OS type
      set_fact:
        os_type: "{{ ansible_facts['distribution'] }}"

    - name: Check if python3-setuptools is installed
      command: "python3 -c 'import setuptools'"
      register: setuptools_check
      ignore_errors: true

    - name: Install python3-setuptools if not present
      package:
        name: "{{ 'python3-setuptools' if os_type in ['CentOS', 'RedHat'] else 'python3-setuptools' }}"
        state: present
      become: yes
      when: setuptools_check.rc != 0

    - name: Check if pymysql is installed
      command: "python3 -c 'import pymysql'"
      register: pymysql_check
      ignore_errors: true

    - name: Install pymysql if not present
      command: pip3 install pymysql
      become: yes
      when: pymysql_check.rc != 0

    - name: download python script
      command: wget http://10.21.100.97/Software/Windows_Software/Scripts/Linux_Scripts/Ansible_Scripts/update_software.py -O /tmp/update_software.py
      become: yes

    - name: Run Python script
      command: "python3 /tmp/update_software.py"
      register: python_output
      become: yes

    - name: Show Python script output
      debug:
        msg: "{{ python_output.stdout }}"
