---
- name: Transfer and run Python script
  hosts: all
  gather_facts: yes

  tasks:
    - name: Install required packages for CentOS and Red Hat
      yum:
        name: "{{ item }}"
        state: present
      when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'
      loop:
        - python3-setuptools
        - python3-pymysql
      become: yes

    - name: Install required packages for Ubuntu and Debian
      apt:
        name: "{{ item }}"
        state: present
      when: ansible_facts['distribution'] == 'Ubuntu' or ansible_facts['distribution'] == 'Debian'
      loop:
        - python3-setuptools
        - python3-pymysql
      become: yes

    - name: Download Python Script
      get_url:
        url: "http://10.21.100.97/Software/Scripts/Linux_Scripts/Ansible_Scripts/update_software.py"
        dest: "/tmp/update_software.py"

    - name: Run Python script
      command: "python3 /tmp/update_software.py"
      register: python_output
      become: yes

    - name: Show Python script output
      debug:
        msg: "{{ python_output.stdout }}"
