---
- name: Transfer and run Python script
  hosts: all
  gather_facts: no
  vars:
    win_share_path: "http://10.21.100.97/Software/Scripts/Linux_Scripts/Ansible_Scripts/"  # Windows 共享路径
    python_script_name: 'main.py'  # Python 脚本文件名
    local_python_script: "/tmp/{{ python_script_name }}"  # 本地保存的 Python 脚本路径
  tasks:
    - name: Transfer Python script from Windows share
      win_copy:
        src: "{{ win_share_path }}/{{ python_script_name }}"
        dest: "{{ local_python_script }}"
      register: copy_result

    - name: Run Python script
      command: "python {{ local_python_script }}"
      register: python_output
      when: copy_result.changed

    - name: Show Python script output
      debug:
        msg: "{{ python_output.stdout }}"
